cc_library(
    name = "v2021_2_cc",
    srcs = glob([
        "v2021_2/**/*.h",
    ]),
    copts = ["-Ivitis/v2012_2/"],
    strip_include_prefix="external/com_cruxml_rules_xilinx/",
    visibility = ["//visibility:public"],
)
